### ISSUE TITLE
How to use without workers

### ISSUE THREAD

**Issue by AdrianDiazCode** [tomitank/tomitankChess#2]
Hi, great project, I'm planning to test it on a react native app but I can't see documentation on how to use it without workers, since RN doesn't allow them, thakns a lot

**Comment by tomitank** [comment]
Hy!
Automatically detects if there is a worker. All you have to do is write the UI.
Something like:
```
if (typeof Worker == 'undefined') {
	onMessage({ data: /*UCI commands*/ });
}
```
