### ISSUE TITLE
Bug: Host detection fails on iOS

### ISSUE THREAD

**Issue by lukas-dachtler** [tomitank/tomitankChess#4]
### Description:
I noticed that the WebWorker wouldn't send any messages back to my app so I investigated further and as it turns out iOS fails the following check in your code:
```javascript
if (typeof Worker != 'undefined') { // WebWorker
	UI_HOST = HOST_WORKER;
}
```
This means the default value of `var UI_HOST = HOST_WEB` is never overwritten and therefore all the messaging is skipped making the entire engine unfunctional on iOS.

---
### Testing:
I've copied your host detection code in both JavaScript files. The output (`UI_HOST`) is displayed in the input boxes. These 2 values are the same on desktop but differ on iOS.
The codepen: https://codepen.io/alphaceph/project/editor/Aoomgp

**Comment by tomitank** [comment]
Hi!
What environment did you test in? (cordova projekt?, safari web browser, other?)
Webworker working only in web browser. (if it's enabled)

**Comment by lukas-dachtler** [comment]
I tested various browsers but internally they all use the same WebKit engine anyways. WebWorkers are supported on iOS (https://caniuse.com/webworkers) so I would expect the chess engine to use them. The code mentioned above however is checking for WebWorker support inside of an already running WebWorker.
> Note: nested workers are not yet implemented in WebKit
https://developer.mozilla.org/en-US/docs/Web/API/Worker

**Comment by tomitank** [comment]
I don't understand. Please try out on another iOS device.
It worked on every iOS device I saw using a web worker.
Important: on localhost you will not be able to call the web worker (as a external file). This is not supported by browsers.

**Comment by lukas-dachtler** [comment]
I'm certain this is not related to the device. Alright let's start from the beginning to make sure there are no misunderstandings. I'll refer to the simplified example from my CodePen:

1. Are the last few lines of `main.js` the correct way to initialize your chess engine on iOS using a WebWorker?

2. What output do you get for both text boxes using an iOS device?

**Comment by tomitank** [comment]
Instead of you call worker.js try out this code directly in main.js:

```
var blobURL = URL.createObjectURL( new Blob([
	`if (typeof Worker != "undefined") {
		postMessage('4');
	} else {
		postMessage('0');
	}`
], { type: 'application/javascript' } ) );

var w = new Worker( blobURL );

URL.revokeObjectURL( blobURL );

w.onmessage = function (m) {
  alert(m.data);
};

```

**Comment by lukas-dachtler** [comment]
Same problem. As I mentioned iOS/ WebKit doesn't allow nested WebWorkers so you can't check for `typeof Worker` inside of a WebWorker. Instead you would have to check if the script itself is running in a WebWorker as shown here for example: https://gist.github.com/miguelmota/a0c9aa9398507e606a6e

I've updated the CodePen to reflect both new versions (blob and fixed). On iOS you should be getting the following output now:
- 4 (checking for WebWorker support on main thread)
- 0 (checking for nested WebWorkers)
- 0 (checking for nested WebWorkers via Blob)
- 4 (checking if script is running inside a WebWorker) -> see `worker_fixed.js:8`

**Comment by tomitank** [comment]
You're right!
WorkerGlobalScope is work on iOS as well.
I used HOST_TANKY and i never got a error.
I updated the code.

Thanks,
Tamás
