### ISSUE TITLE
[Question] Magic numbers?

### ISSUE THREAD

**Issue by guillaumegarcia13** [tomitank/tomitankChess#5]
Fantastic work you pulled up here! 👍🏻

I was wondering about some parts of your code that look like "bunch of magic numbers" for newcomers! 😅
(eg. CHESS_NN)

How are they optimized? (rule of thumb or using heuristic optimization [first idea in mind would be to use genetic algorithms and compete against an evaluation program])

**Update**
Got some answers here: https://chessengines.blogspot.com/2021/01/chess-engine-tomitankchess-50.html

**Comment by tomitank** [comment]
Hi!
CHESS_NN trained with own code. It's very close to "basic - classic full connected" neural network, with a little change.
you can find lot of videos about it on the internet.
My favorit site: http://neuralnetworksanddeeplearning.com/
The evaluation variables trainied with logistic regression (with one preceptron)

**Comment by guillaumegarcia13** [comment]
Thanks!

I managed to build this frontend using your engine and [chessboardjs](https://chessboardjs.com/).
![ChessUI5](https://user-images.githubusercontent.com/2786038/131466803-d0ed824e-87df-47e1-811c-0a4cc1abfed0.png)
