### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Krzychumag** [tomitank/tomitankChess#6]
Hi Tamás,

Can I ask you for help in installing the chess engine tomitankChess 5.1 x64. I am using the Cutochess 1.2 GUI under Windows 10 x64. I have installed Node.js from https://nodejs.org/en/. The program is installed in C:\Program Files\nodejs. Can I ask you to write how to enter the appropriate commands in the window below. Thank you in advance for any help.
![Prośba](https://user-images.githubusercontent.com/30792281/174016224-168e19d3-749e-4098-86b2-d57b71625f10.jpg)

Sincerely
Krzysztof

**Comment by tomitank** [comment]
> Hi Tamás,
> 
> Can I ask you for help in installing the chess engine tomitankChess 5.1 x64. I am using the Cutochess 1.2 GUI under Windows 10 x64. I have installed Node.js from https://nodejs.org/en/. The program is installed in C:\Program Files\nodejs. Can I ask you to write how to enter the appropriate commands in the window below. Thank you in advance for any help. ![Prośba](https://user-images.githubusercontent.com/30792281/174016224-168e19d3-749e-4098-86b2-d57b71625f10.jpg)
> 
> Sincerely Krzysztof

Import part, that you don't use white space in the path name.
Name: tomitankChess
Command: nodejs.exe path but after that whitespace and the tomitankChess.js path
example: C:\nodejs.exe d:\tomitankChess.js
